### ISSUE TITLE
Language Option

### ISSUE THREAD

**Issue by usengun** [afet-yonetim-sistemi/ays-fe-landing#14]
Dil secenegini incelerken diger dil seceneginin ekranda gorunmedigini fark ettim, listedeki diger dil secenegini goruntulemek icin uzerine gelmek gerekiyor, felaket aninda gorunur olmasi acisindan dil secenegine tiklandiginda her iki dilinde gozukmesinin daha anlamli olacagini dusunuyorum

**Comment by agitrubard** [comment]
@usengun Selamlar,
Issue açarken aşağıdaki 3 kısmı da doldurabilir misin?
![image](https://github.com/afet-yonetim-sistemi/ays-fe-landing/assets/61833677/e33e260a-8996-4211-9e63-7aaa5dcc4bae)
