### ISSUE TITLE
Sayfanın Ölçek Olarak Küçültülmesi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-fe-landing#15]
Sayfaya girildiğinde ölçek olarak küçültülmesi görsel olarak daha iyi bir hâle getirebilir. Örnek olarak aşağıdaya iki görsel ekliyor olacam, bunlara dikkat ederek geliştirmeleri yapabiliriz.

---

**Mevcut Ekran;**
![image](https://github.com/afet-yonetim-sistemi/ays-fe-landing/assets/61833677/78b686c4-4b91-4437-96c8-4bd8f775dd14)

**Olması Gereken Ekran;**
![image](https://github.com/afet-yonetim-sistemi/ays-fe-landing/assets/61833677/2923da50-1ecb-414e-93c9-6a9671d7e4a7)

**Comment by rasitcolakel** [comment]
Bu issue için [bu video](https://youtu.be/rYXxDQTTkYo?si=mFblWMa6Yq9q4pcW) izlenebilir
