### ISSUE TITLE
LinkedIn Erişim Iconunun Eklenmesi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-fe-landing#29]
Bu issue ile birlikte aşağıdaki görsellerde bulunan işaretli kısımlarda GitHub ve Discord iconlarında olduğu gibi LinkedIn erişim iconunun eklenmesi gerekmektedir.

**LinkedIn URL:** https://www.linkedin.com/company/afetyonetimsistemi

---

Icon sıralaması aşağıdaki gibi olmalıdır;

| LinkedIn | GitHub | Discord |
|---------|---------|---------|

---
![Screenshot 2023-10-02 at 9 43 29 AM](https://github.com/afet-yonetim-sistemi/ays-fe-landing/assets/61833677/9b59a418-e351-42bd-9b17-161300db0b02)
![Screenshot 2023-10-02 at 9 44 01 AM](https://github.com/afet-yonetim-sistemi/ays-fe-landing/assets/61833677/d94b9d5f-39a6-4c22-875c-66850cb9ede4)

**Comment by rasitcolakel** [comment]
Closed with the PR #30

**Comment by agitrubard** [comment]
@rasitcolakel @beyzanur-seyhan pull requesti açtıktan sonra buraya mesaj yazmak yerine pull request ve issue'yu ilişkilendirebilir misiniz?
