### ISSUE TITLE
Improvement for Design

### ISSUE THREAD

**Issue by WizardLizard8998** [afet-yonetim-sistemi/ays-fe-landing#3]

**Comment by agitrubard** [comment]
Burada UI/UX tasarımı bekleniyor @busraselimoglu bize bu konuda destek olacak, hazırlandıktan sonra buraya ekliyor olacağız sonrasında geliştirmeye başlanabilir.

**Comment by agitrubard** [comment]
**FE Landing UI/UX**
https://www.figma.com/file/BEl5DcvE3GORgC903FWESA/ays-landingpage?type=design&node-id=0-1&mode=design

**Comment by agitrubard** [comment]
@WizardLizard8998 bu issue neden kapatıldı?

**Comment by agitrubard** [comment]
@erencansev @kevseroz @rasitcolakel Pull Request'ler issue ile ilişkilendirilmemişti, bu ilişkilendirmeyi yaptım, bundan sonrakilerde dikkat edebilirsek çok iyi olur

**Comment by agitrubard** [comment]
@erencansev @kevseroz @rasitcolakel Issue içerisindeki label ve board üzerindeki statüsü güncellenmemişti, bu güncellemeyi yaptım ama bundan sonrakilerde dikkat edebilirsek çok iyi olur
