### ISSUE TITLE
README.md Duzenlenmesi

### ISSUE THREAD

**Issue by Rapter1990** [afet-yonetim-sistemi/ays-fe-landing#37]
Bu issue'da Readme.md dosyasinin landing page bilgisi verilmesi, gerekli configuration bilgisinin verilmesi (projeyi nasil ayaga kaldirabiliriz) yeniden yazilmasi gerekmektedir. Boylece landing page yeni gelen biri repoyu kolayca anlayabilir.

**Comment by agitrubard** [comment]
#1 numaralı issue'da yapıldığı için issue kapatıldı
