### ISSUE TITLE
google maps isn't working 

### ISSUE THREAD

**Issue by WizardLizard8998** [afet-yonetim-sistemi/ays-fe-landing#5]
google maps isn't working after last commit. if you have any information about google maps API please contact me

**Comment by agitrubard** [comment]
@WizardLizard8998 ilk aşamada buraya ihtiyaç olmayabilir, Landing Page içerisinde bir map ihtiyacımız yok şu an temel anlamda ne yapıyoruz, biz kimiz ve bize nasıl ulaşabilirsiniz gibi konuları içeriyor olacak.
